### ISSUE TITLE
Failing to request data

### ISSUE THREAD

**Issue by Beheroth** [Snekw/Wf#1]
All url links respond with error 500. 

```
{
  "error": {
    "message": "Failed at requesting data.",
    "data": {},
    "inner": {
      "message": "Failed to parse or find revisions.",
      "data": {},
      "inner": {},
      "stack": "Error: Failed to parse or find revisions.\n    at IncomingMessage.res.on (/var/www/Wf/cache.js:113:27)\n    at IncomingMessage.emit (events.js:185:15)\n    at endReadableNT (_stream_readable.js:1106:12)\n    at process._tickCallback (internal/process/next_tick.js:178:19)",
      "full": {
        "error": {}
      }
    },
    "stack": "Error: Failed at requesting data.\n    at Cache._getRequest.then.catch.err (/var/www/Wf/cache.js:164:29)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:182:7)",
    "full": {
      "error": {
        "error": {}
      }
    }
  }
}
```

**Comment by Snekw** [comment]
Apparently there had been a change to the wikimedia API that I'm using. I have fixed this now. Thanks for letting me know that it's broken. :)
