### ISSUE TITLE
Failing to request data on /weapon-wiki

### ISSUE THREAD

**Issue by LilPisces** [Snekw/Wf#3]
/weapon-wiki respond with error 500.
```
{
  "error": {
    "message": "Failed at requesting data.",
    "data": {},
    "inner": {
      "message": "Failed to get lua data.",
      "data": {},
      "inner": {},
      "stack": "Error: Failed to get lua data.\n    at getLuaObject.then.catch.err (/var/www/Wf/cache.js:110:31)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:182:7)",
      "full": {
        "error": "lua5.3: ./json.lua:94: unexpected number value '-inf'\nstack traceback:\n\t[C]: in function 'error'\n\t./json.lua:94: in function <./json.lua:91>\n\t(...tail calls...)\n\t./json.lua:78: in function <./json.lua:44>\n\t(...tail calls...)\n\t./json.lua:78: in function <./json.lua:44>\n\t(...tail calls...)\n\t./json.lua:78: in function <./json.lua:44>\n\t(...tail calls...)\n\t./json.lua:78: in function <./json.lua:44>\n\t(...tail calls...)\n\t./json.lua:120: in function 'json.encode'\n\t./luaObjectToJson.lua:26: in main chunk\n\t[C]: in ?\n"
      }
    },
    "stack": "Error: Failed at requesting data.\n    at Cache._getRequest.then.catch.err (/var/www/Wf/cache.js:164:29)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:182:7)",
    "full": {
      "error": {
        "error": "lua5.3: ./json.lua:94: unexpected number value '-inf'\nstack traceback:\n\t[C]: in function 'error'\n\t./json.lua:94: in function <./json.lua:91>\n\t(...tail calls...)\n\t./json.lua:78: in function <./json.lua:44>\n\t(...tail calls...)\n\t./json.lua:78: in function <./json.lua:44>\n\t(...tail calls...)\n\t./json.lua:78: in function <./json.lua:44>\n\t(...tail calls...)\n\t./json.lua:78: in function <./json.lua:44>\n\t(...tail calls...)\n\t./json.lua:120: in function 'json.encode'\n\t./luaObjectToJson.lua:26: in main chunk\n\t[C]: in ?\n"
      }
    }
  }
}
```

**Comment by Snekw** [comment]
I have fixed the `/weapons-wiki` route now. Couple of other routes seem to also throw errors and I will be looking into those next.
