### ISSUE TITLE
 Failing to request data on /void-wiki, /version-wiki, /missions-wiki

### ISSUE THREAD

**Issue by OchseGit** [Snekw/Wf#5]
Hi Snekw!
I like your API and use it to get Void Relics to track my progress with prime parts.
Unfortunately some APIs have stopped working and I wonder if you can take a look and fix it again.

Thanks in advance for your work! I appreciate it!

**[https://wf.snekw.com/void-wiki](https://wf.snekw.com/void-wiki)**
```
{
   "error":{
      "message":"Failed at requesting data.",
      "data":{
         
      },
      "inner":{
         "message":"Failed to get lua data.",
         "data":{
            
         },
         "inner":{
            
         },
         "stack":"Error: Failed to get lua data.\n    at getLuaObject.then.catch.err (/var/www/Wf/cache.js:110:31)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:182:7)",
         "full":{
            "error":"lua5.3: [string \"...\"]:13: module 'Module:Shared' not found:\n\tno field package.preload['Module:Shared']\n\tno file '/usr/local/share/lua/5.3/Module:Shared.lua'\n\tno file '/usr/local/share/lua/5.3/Module:Shared/init.lua'\n\tno file '/usr/local/lib/lua/5.3/Module:Shared.lua'\n\tno file '/usr/local/lib/lua/5.3/Module:Shared/init.lua'\n\tno file '/usr/share/lua/5.3/Module:Shared.lua'\n\tno file '/usr/share/lua/5.3/Module:Shared/init.lua'\n\tno file './Module:Shared.lua'\n\tno file './Module:Shared/init.lua'\n\tno file '/usr/local/lib/lua/5.3/Module:Shared.so'\n\tno file '/usr/lib/x86_64-linux-gnu/lua/5.3/Module:Shared.so'\n\tno file '/usr/lib/lua/5.3/Module:Shared.so'\n\tno file '/usr/local/lib/lua/5.3/loadall.so'\n\tno file './Module:Shared.so'\nstack traceback:\n\t[C]: in function 'require'\n\t[string \"...\"]:13: in local 'f'\n\t./luaObjectToJson.lua:25: in main chunk\n\t[C]: in ?\n"
         }
      },
      "stack":"Error: Failed at requesting data.\n    at Cache._getRequest.then.catch.err (/var/www/Wf/cache.js:164:29)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:182:7)",
      "full":{
         "error":{
            "error":"lua5.3: [string \"...\"]:13: module 'Module:Shared' not found:\n\tno field package.preload['Module:Shared']\n\tno file '/usr/local/share/lua/5.3/Module:Shared.lua'\n\tno file '/usr/local/share/lua/5.3/Module:Shared/init.lua'\n\tno file '/usr/local/lib/lua/5.3/Module:Shared.lua'\n\tno file '/usr/local/lib/lua/5.3/Module:Shared/init.lua'\n\tno file '/usr/share/lua/5.3/Module:Shared.lua'\n\tno file '/usr/share/lua/5.3/Module:Shared/init.lua'\n\tno file './Module:Shared.lua'\n\tno file './Module:Shared/init.lua'\n\tno file '/usr/local/lib/lua/5.3/Module:Shared.so'\n\tno file '/usr/lib/x86_64-linux-gnu/lua/5.3/Module:Shared.so'\n\tno file '/usr/lib/lua/5.3/Module:Shared.so'\n\tno file '/usr/local/lib/lua/5.3/loadall.so'\n\tno file './Module:Shared.so'\nstack traceback:\n\t[C]: in function 'require'\n\t[string \"...\"]:13: in local 'f'\n\t./luaObjectToJson.lua:25: in main chunk\n\t[C]: in ?\n"
         }
      }
   }
}
```

**[https://wf.snekw.com/version-wiki](https://wf.snekw.com/version-wiki)**
```
{
   "error":{
      "message":"Failed at requesting data.",
      "data":{
         
      },
      "inner":{
         "message":"Failed to get lua data.",
         "data":{
            
         },
         "inner":{
            
         },
         "stack":"Error: Failed to get lua data.\n    at getLuaObject.then.catch.err (/var/www/Wf/cache.js:110:31)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:182:7)",
         "full":{
            "error":"lua5.3: ./json.lua:73: invalid table: mixed or invalid key types\nstack traceback:\n\t[C]: in function 'error'\n\t./json.lua:73: in function <./json.lua:59>\n\t(...tail calls...)\n\t./json.lua:93: in function <./json.lua:59>\n\t(...tail calls...)\n\t./json.lua:93: in function <./json.lua:59>\n\t(...tail calls...)\n\t./json.lua:138: in function 'json.encode'\n\t./luaObjectToJson.lua:26: in main chunk\n\t[C]: in ?\n"
         }
      },
      "stack":"Error: Failed at requesting data.\n    at Cache._getRequest.then.catch.err (/var/www/Wf/cache.js:164:29)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:182:7)",
      "full":{
         "error":{
            "error":"lua5.3: ./json.lua:73: invalid table: mixed or invalid key types\nstack traceback:\n\t[C]: in function 'error'\n\t./json.lua:73: in function <./json.lua:59>\n\t(...tail calls...)\n\t./json.lua:93: in function <./json.lua:59>\n\t(...tail calls...)\n\t./json.lua:93: in function <./json.lua:59>\n\t(...tail calls...)\n\t./json.lua:138: in function 'json.encode'\n\t./luaObjectToJson.lua:26: in main chunk\n\t[C]: in ?\n"
         }
      }
   }
}
```

**[https://wf.snekw.com/missions-wiki](https://wf.snekw.com/missions-wiki)**
```
{
   "error":{
      "message":"Failed at requesting data.",
      "data":{
         
      },
      "inner":{
         "message":"Failed to get lua data.",
         "data":{
            
         },
         "inner":{
            
         },
         "stack":"Error: Failed to get lua data.\n    at getLuaObject.then.catch.err (/var/www/Wf/cache.js:110:31)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:182:7)",
         "full":{
            "error":"lua5.3: [string \"local MissionData = {...\"]:357: attempt to call a table value (field 'vars')\nstack traceback:\n\t[string \"local MissionData = {...\"]:357: in local 'f'\n\t./luaObjectToJson.lua:25: in main chunk\n\t[C]: in ?\n"
         }
      },
      "stack":"Error: Failed at requesting data.\n    at Cache._getRequest.then.catch.err (/var/www/Wf/cache.js:164:29)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:182:7)",
      "full":{
         "error":{
            "error":"lua5.3: [string \"local MissionData = {...\"]:357: attempt to call a table value (field 'vars')\nstack traceback:\n\t[string \"local MissionData = {...\"]:357: in local 'f'\n\t./luaObjectToJson.lua:25: in main chunk\n\t[C]: in ?\n"
         }
      }
   }
}
```

**Comment by Snekw** [comment]
Fixed in 0e98bc899f963eb7df2adf488af69ffacee3753a. The fix has also been pushed to https://wf.snekw.com.
